beaker-project/beaker

- .packit.yaml
> Add new check for RPM build on Fedora 32

- IntegrationTests/src/bkr/inttest/labcontroller/install-failure-logs/rhvh44-no-free-space-thinp.txt
- LabController/src/bkr/labcontroller/install-failure-patterns/anaconda-rhvh4-no-free-space-thinp
This will kill installation when this happens + report the error.
The test dataset is taken from actual run :)
Fixes: #12 
> Detect thinp drive size error in installation

- .packit.yaml
Disable comments in PR made by Packit
> Disable notifications during PR from Packit

- Server/bkr/server/model/distrolibrary.py
> Make sure RHVH 4.4+ is using RHEL 8 configuration

- LabController/src/bkr/labcontroller/expire_distros.py
> Fix behavior for --remove-all in beaker-expire-distros

- Server/bkr/server/tools/beakerd.py
> Add comment for provision rollback

- Server/bkr/server/static/javascript/primary_secondary.js
- Server/bkr/server/static/javascript/product_manager.js
- Server/bkr/server/static/javascript/rettag_manager_v2.js
- Server/bkr/server/templates/job-old.kid
- Server/server.cfg
- documentation/architecture-guide/beaker-differences.rst
Remove all master/slave references.
> Update terminology used in Beaker

- Client/src/bkr/client/commands/cmd_system_modify.py
- IntegrationTests/src/bkr/inttest/client/test_system_modify.py
The system-create command has many more settings that can be set,
especially for power options.
Add these settings to the system-modify command so you can modify them
via the command line. Previously could only change them via the GUI.
Fixes: #36
> system-modify: Add additional settings to be able to modify

- documentation/admin-guide/system-requirements.rst
> Update requirements for Beaker

- .packit.yaml
> Drop Fedora 30 from Packit

- documentation/user-guide/customizing-installation.rst
- documentation/user-guide/systems/adding.rst
There is a method to unset install options which is not documented.
This changeset provides that information.
Bug: 1711063
> DOC: Doc how to unset install options

- IntegrationTests/src/bkr/inttest/server/selenium/test_system_search.py
The previous development team didn't expect to surpass 2012. 
But.. Here we are. Bumping those _rocky numbers_.
Fixes: #38
> Fix failing E2E test

- documentation/whats-new/index.rst
- documentation/whats-new/release-28.rst
> Release 28 notes

- Server/bkr/server/messaging.py
- beaker.spec
> Disable messaging when qpid is not available

- .packit.yaml
> Fedora 31 EOL'd

- Client/src/bkr/client/commands/cmd_loan_request.py
This PR fixes https://github.com/beaker-project/beaker/issues/72
> Add a bkr loan-request command

- Server/bkr/server/authentication.py
Following things changed:
- Removed whole XMLRPC
- Removed Flask Oauth2 and Kerberos
> Expose only BasicAuth API

- Server/bkr/server/authentication.py
Small change.
Use proper headers to accept usr/pass combination.
> Use Authorization header for BasicAuth

- Server/bkr/server/controllers.py
- Server/bkr/server/watchdog.py
- Server/bkr/server/wsgi.py
> REST API endpoint for watchdog

- Server/bkr/server/utilisation.py
Pretty simple this one
- Removed session from TurboGears (🎉), so we are ready to ditch it.
- Style clean up, this file was literally not readable.
> Update utilisation 

- Server/bkr/server/model/activity.py
Simple one
- Drop session from TurboGears
- Remove Unicode keyword as this doesn't exist in Python 3
> Drop TurboGears from Activity

- .stickler.yml
https://stickler-ci.com/docs#black
Closes: #103
> Enable the black check in .stickler.yml

- .stickler.yml
https://black.readthedocs.io/en/stable/compatible_configs.html#flake8
> Add ignore rules for flake8 so it won't fight with black

- Common/bkr/common/api.py
- Common/bkr/common/default.conf
This will help to integrate new CLI / Lab Controller as XMLRPC login is gone.
> Create API helper

- Client/src/bkr/future/__init__.py
- Client/src/bkr/future/api.py
- Client/src/bkr/future/base.py
- Client/src/bkr/future/config.py
- Client/src/bkr/future/group/__init__.py
- Client/src/bkr/future/job/__init__.py
- Client/src/bkr/future/labcontroller/__init__.py
- Client/src/bkr/future/loan/__init__.py
- Client/src/bkr/future/policy/__init__.py
- Client/src/bkr/future/pool/__init__.py
- Client/src/bkr/future/system/__init__.py
- Client/src/bkr/future/task/__init__.py
- Client/src/bkr/future/user/__init__.py
- Client/src/bkr/future/user/whoami.py
- Client/src/bkr/future/watchdog/__init__.py
- Client/src/bkr/future/workflow/__init__.py
- beaker.spec
> New client layout

- Client/src/bkr/future/group/__init__.py
- Client/src/bkr/future/group/create.py
- Client/src/bkr/future/group/list_groups.py
- Client/src/bkr/future/group/members.py
- Client/src/bkr/future/group/modify.py
Not sure about sphinx descriptions yet. Maybe we will move them out in the final design.
> Add group commands to future CLI

- Server/bkr/server/recipes.py
> Extend Watchdog API

- Client/src/bkr/future/param_types.py
- Client/src/bkr/future/taskspec.py
- Client/src/bkr/future/watchdog/__init__.py
- Client/src/bkr/future/watchdog/extend.py
- Client/src/bkr/future/watchdog/list_watchdog.py
- Client/src/bkr/future/watchdog/set_watchdog.py
Add all watchdog commands that are currently supported.
> Add watchdog commands

- Client/src/bkr/future/user/__init__.py
- Client/src/bkr/future/user/delegate/__init__.py
- Client/src/bkr/future/user/delegate/add.py
- Client/src/bkr/future/user/delegate/remove.py
- Client/src/bkr/future/user/remove.py
- Client/src/bkr/future/user/update.py
This is same set of commands as we had in old CLI.
No new functionality yet. We may add more features in the future.
> Add user commands

- Server/bkr/server/app.py
- Server/bkr/server/cors_core.py
- Server/bkr/server/cors_extension.py
Enable CORS otherwise, our new dashboard can't use it.
This should be a temporary solution and replaced when the whole app is running Flask and we know target environment.
> Enable CORS

- Server/bkr/server/cors_core.py
- Server/bkr/server/cors_extension.py
> Make CORS* import Python 6

- Client/src/bkr/future/loan/__init__.py
- Client/src/bkr/future/loan/grant.py
- Client/src/bkr/future/loan/request.py
- Client/src/bkr/future/loan/return_grant.py
Add all loan commands that were supported.
> Add loan commands to CLI

- Server/bkr/server/app.py
> Allow to CORS credentials

- .github/workflows/review-checks.yml
> Include Node 20 for older glibc

- .github/workflows/review-checks.yml
Enable server unit tests for EL7
> Enable server unit tests
