beaker-project/beaker

- Client/src/bkr/client/commands/cmd_task_delete.py
- documentation/whats-new/release-27.rst
We covered everything in Beaker for now.
It would be nice to ship new release to upstream.
We have 2 RFEs covered and 1 issue.
- Users can use new ks_meta called ks_keyword which allows users to change kickstart variable on kernel cmdline.
- New command to erase task from Beaker's task library
- Fix for corrupted installation in RHVH.
> docs: release notes 27.4

- IntegrationTests/src/bkr/inttest/labcontroller/test_proxy.py
- IntegrationTests/src/bkr/inttest/server/kickstarts/AtomicHost-defaults.expected
- IntegrationTests/src/bkr/inttest/server/kickstarts/Fedora18-harness-contained-custom.expected
- IntegrationTests/src/bkr/inttest/server/kickstarts/Fedora18-harness-contained.expected
- IntegrationTests/src/bkr/inttest/server/kickstarts/Fedora18-scheduler-defaults.expected
- IntegrationTests/src/bkr/inttest/server/kickstarts/Fedorarawhide-scheduler-defaults.expected
- IntegrationTests/src/bkr/inttest/server/kickstarts/RHVH-defaults.expected
- IntegrationTests/src/bkr/inttest/server/kickstarts/RedHatEnterpriseLinux7-scheduler-defaults.expected
- IntegrationTests/src/bkr/inttest/server/kickstarts/RedHatEnterpriseLinux7-scheduler-manual.expected
- IntegrationTests/src/bkr/inttest/server/kickstarts/RedHatEnterpriseLinuxAlternateArchitectures7-scheduler-defaults.expected
- IntegrationTests/src/bkr/inttest/server/test_kickstart.py
- LabController/src/bkr/labcontroller/main.py
- LabController/src/bkr/labcontroller/proxy.py
- Server/bkr/server/kickstarts/default
- Server/bkr/server/model/distrolibrary.py
- Server/bkr/server/recipes.py
- Server/bkr/server/snippets/onerror
- documentation/user-guide/customizing-installation.rst
At this point, we are scraping the output of `console.log` and trying to match with `known` issues. This may help a bit but this is not definitely good solution.
Because
- Not all machines have console attached - In the worst case there is no console for any machine
- Strings are always changing and we have to add a new 
- Reservesys Workflow completely ignores installation failures. It has a disabled panic feature by default.
Instead of that, we may use the kickstart feature `%onerror` [docs](https://pykickstart.readthedocs.io/en/latest/kickstart-docs.html#chapter-7-handling-errors)
This should be shipped in RHEL7+. This means that all Fedoras will be covered by this as well.
> Make the installation error detection more reliable

- IntegrationTests/src/bkr/inttest/labcontroller/test_watchdog.py
- LabController/labcontroller.conf
- LabController/src/bkr/labcontroller/provision.py
- LabController/src/bkr/labcontroller/proxy.py
- LabController/src/bkr/labcontroller/utils.py
Support console files with the name of $CONSOLE_LOGS/$FQDN*
For example:
If CONSOLE_LOGS=/var/consoles and the FQDN=test.example.com
Then the following files will be logged as console files:
/var/consoles/test.example.com -> console.log
/var/consoles/test.example.com-bmc -> console-bmc.log
/var/consoles/test.example.com-serial2 -> console-serial2.log
Bug: 1771666
> Add multi-console log support

- Server/bkr/server/identity.py
This is a quality of life improvement. Previous beaker used session
cookies. So when you close your browser the cookie would disappear and
then you would need to login again the next time you went to the
server.
Now we set a persistent cookie which has its expiration set based on
the "visit.timeout" value in the Beaker server.cfg file.
Fixes: #19
> Change authentication cookie to a persistent cookie

- Server/bkr/server/distrotrees.py
When calling distro-trees-list now also return ks_meta and
kernel_options_post. Currently it already returns kernel_options.
This is useful for scripting when wanting to know what the ks_meta and
kernel_options_post values are.
This will now be seen when doing:
$ bkr distro-trees-list --format=json
> distro-trees-list: Return ks_meta & kernel_options_post

- Server/bkr/server/model/distrolibrary.py
Make sure we can recognize all RHEL like products and treat them in the same manner.
> Recognize all RHEL like products

- IntegrationTests/src/bkr/inttest/server/kickstarts/RedHatEnterpriseLinux6-manual-defaults-beaker-create-kickstart.expected
- IntegrationTests/src/bkr/inttest/server/kickstarts/RedHatEnterpriseLinux6-scheduler-defaults-beaker-create-kickstart.expected
- Server/bkr/server/snippets/lab_env
when using restraint to run tests in DCI we set LOOKASIDE variable
from the job xml but couldn't figure out why it wasn't being set
when the job ran.  This default was overwriting our value.
We worked around this by creating a /etc/beaker/snippets/lab_env
file with nothing in it.
Change-Id: Ie4d66988cc2ccc08c58239d3d23a139027139426
> Don't set empty default values

- IntegrationTests/src/bkr/inttest/server/test_database_migration.py
- IntegrationTests/src/bkr/inttest/server/test_kickstart.py
- Server/bkr/server/alembic/versions/4b3a6065eba2_fix_size_of_rendered_kickstart.py
- Server/bkr/server/kickstart.py
- Server/bkr/server/model/installation.py
- Server/bkr/server/model/scheduler.py
- Server/bkr/server/tools/beakerd.py
At this point is really easy to breach 65k characters in rendered kickstart.
The easiest way to achieve that is to running jobs as Group and ask them
to add their SSH key into account. Beaker will take every single one SSH key
and put it into kickstart. The database will fail to store it and we will end up an infinite loop.
Where scheduler is trying to reschedule it again and again.
Bug: [1796851](https://bugzilla.redhat.com/show_bug.cgi?id=1796851)
> Fix kickstart size limitation

- IntegrationTests/src/bkr/inttest/server/test_kickstart.py
- Server/bkr/server/snippets/harness
Following definition should be considered as valid
```XML
<recipe ks_meta="harness=restraint-rhts-0.1.44 harness='restraint-rhts beakerlib-redhat' ">
```
Bug: [1803555](https://bugzilla.redhat.com/show_bug.cgi?id=1803555)
It is expected that we will merge all items and make DNF resolve the situation
> Allow user to define harness in ks_meta multiple times

- IntegrationTests/src/bkr/inttest/labcontroller/test_proxy.py
- LabController/src/bkr/labcontroller/main.py
- LabController/src/bkr/labcontroller/proxy.py
- documentation/alternative-harnesses/index.rst
At this point, we are missing support for power management (controlled by Beaker) via HTTP API.
However, you can achieve this through the XMLRPC API. This PR should address this problem and mimic the behavior.
Fixes: #17 
> Add support to control power from harness API

- IntegrationTests/src/bkr/inttest/labcontroller/test_distro_import.py
- LabController/src/bkr/labcontroller/distro_import.py
- documentation/admin-guide/man/beaker-import.rst
When beaker-import does an import it will by default overwrite any
''Install Options' (Kickstart Metadata, Kernel Options, & Kernel
Options Post) that may already be set for the distro.
This new option --preserve-install-options will change the behavior so
that it won't overwrite any previously stored values for the distro.
This can be useful when you have multiple lab controllers and roll out
a distro first to one lab controller and spend time setting up the
correct Install Options. Once that is done you decide to do a
beaker-import on the other lab controllers and don't want to lose your
Install Options.
Fixes: #24
> beaker-import: Add --preserve-install-options argument

- IntegrationTests/src/bkr/inttest/server/test_model.py
- Server/bkr/server/model/scheduler.py
Make sure we are not adding `system_type` XML element in case the user already defines `system/type`.
Bug: [1851464](https://bugzilla.redhat.com/show_bug.cgi?id=1851464)
> Don't add XML element system_type when user already defined type

- IntegrationTests/src/bkr/inttest/server/selenium/test_help.py
- Server/bkr/server/config/app.cfg
- Server/bkr/server/templates/master.kid
- documentation/admin-guide/reporting-queries.rst
- documentation/index.rst
At this point we **should** point all incoming issues to GitHub rather than Bugzilla.
> Use reference to GitHub rather than BZ

- documentation/man/bkr.rst
- documentation/user-guide/beaker-provided-tasks.rst
Removing references in documentation to `/distribution/install`. This task should not be used anymore. There is no good reason. Instead of that, we should advertise `/distribution/check-install`.
> Clean up docs from obsolete /distribution/install task

- IntegrationTests/src/bkr/inttest/server/kickstarts/Fedora18-scheduler-defaults.expected
- IntegrationTests/src/bkr/inttest/server/kickstarts/RHVH-defaults.expected
- IntegrationTests/src/bkr/inttest/server/kickstarts/RedHatEnterpriseLinux6-scheduler-defaults-beaker-create-kickstart.expected
- IntegrationTests/src/bkr/inttest/server/kickstarts/RedHatEnterpriseLinux6-scheduler-defaults.expected
- IntegrationTests/src/bkr/inttest/server/kickstarts/RedHatEnterpriseLinux6-scheduler-guest.expected
- IntegrationTests/src/bkr/inttest/server/kickstarts/RedHatEnterpriseLinux6-scheduler-manual.expected
- IntegrationTests/src/bkr/inttest/server/kickstarts/RedHatEnterpriseLinux7-scheduler-defaults.expected
- IntegrationTests/src/bkr/inttest/server/kickstarts/RedHatEnterpriseLinux7-scheduler-manual.expected
- IntegrationTests/src/bkr/inttest/server/kickstarts/RedHatEnterpriseLinuxAlternateArchitectures7-scheduler-defaults.expected
- IntegrationTests/src/bkr/inttest/server/kickstarts/RedHatEnterpriseLinuxServer5-scheduler-defaults.expected
- IntegrationTests/src/bkr/inttest/server/test_kickstart.py
- Server/bkr/server/model/distrolibrary.py
Following topic are covered by this PR:
- By default, Restraint-RHTS is passed as `harness`
- Beah is still usable. The user has to define it in ks_meta. Due to Beah dep limitation user should use a combination of `harness=beah install_task_requires` in `ks_meta`
- Note ` # Task requirements will be installed by the harness ` always appears in `%package` section as Beaker is always taking special threatment to it. No matter if user will define it in kickstart or when it is generated fully by Beaker. 
Fix: #32
> Use Restraint-RHTS as default test harness

- Server/assets/jst/system-power-settings.html
- Server/assets/system-power-settings.js
Users can toggle to see the password assigned to the given machine. By default password is hidden.
_Default:_
_Toggled:_
Fixes: #48 
> Hide power managment password by default

- beaker.spec
We should be more explict about content and what we are putting there.
This is backport from upstream specfile
> Use proper macro for python 3 files

- Client/src/bkr/client/commands/cmd_policy_grant.py
- Client/src/bkr/client/commands/cmd_policy_list.py
- Client/src/bkr/client/commands/cmd_policy_revoke.py
- Client/src/bkr/client/commands/cmd_pool_add.py
- Client/src/bkr/client/commands/cmd_pool_create.py
- Client/src/bkr/client/commands/cmd_pool_delete.py
- Client/src/bkr/client/commands/cmd_pool_modify.py
- Client/src/bkr/client/commands/cmd_pool_remove.py
- Client/src/bkr/client/commands/cmd_update_inventory.py
- IntegrationTests/src/bkr/inttest/server/test_database_migration.py
- LabController/setup.py
- Misc/pylint-errors.cfg
- documentation/admin-guide/kickstarts.rst
- documentation/admin-guide/panic-detection.rst
- documentation/admin-guide/power-commands.rst
Python 2.6 is no longer supported. Our codebase is compatible only with
Python 2.7. In some cases it can be sixed to Python 3.
> Drop Python 2.6 references

- Server/apache/beaker-server.conf
As we are running on top of RHEL 7 we can use mods for GSSAPI rather than using mod_kerberos.
We were struggling with security and compatibility issues with Kerberos.
We should spread this wisdom to default configs as well.
> Kerberos is dead, long live the GSSAPI

- beaker.spec
We can't use `%{version}` macro in specfile for %files section. This is caused by the fact that Packit is changing value of `Version` based on provided tags in repository.
> Drop macro from %files section

- IntegrationTests/src/bkr/inttest/server/kickstarts/AtomicHost-defaults.expected
- IntegrationTests/src/bkr/inttest/server/kickstarts/Fedora18-harness-contained-custom.expected
- IntegrationTests/src/bkr/inttest/server/kickstarts/Fedora18-harness-contained.expected
- IntegrationTests/src/bkr/inttest/server/kickstarts/Fedora18-scheduler-defaults.expected
- IntegrationTests/src/bkr/inttest/server/kickstarts/Fedorarawhide-scheduler-defaults.expected
- IntegrationTests/src/bkr/inttest/server/kickstarts/RHVH-defaults.expected
- IntegrationTests/src/bkr/inttest/server/kickstarts/RedHatEnterpriseLinux6-scheduler-defaults-beaker-create-kickstart.expected
- IntegrationTests/src/bkr/inttest/server/kickstarts/RedHatEnterpriseLinux6-scheduler-defaults.expected
- IntegrationTests/src/bkr/inttest/server/kickstarts/RedHatEnterpriseLinux6-scheduler-guest.expected
- IntegrationTests/src/bkr/inttest/server/kickstarts/RedHatEnterpriseLinux6-scheduler-manual.expected
- IntegrationTests/src/bkr/inttest/server/kickstarts/RedHatEnterpriseLinux7-scheduler-defaults.expected
- IntegrationTests/src/bkr/inttest/server/kickstarts/RedHatEnterpriseLinux7-scheduler-manual.expected
- IntegrationTests/src/bkr/inttest/server/kickstarts/RedHatEnterpriseLinuxAlternateArchitectures7-scheduler-defaults.expected
- IntegrationTests/src/bkr/inttest/server/kickstarts/RedHatEnterpriseLinuxServer5-scheduler-defaults.expected
- Server/bkr/server/snippets/taskrepo
- documentation/user-guide/customizing-installation.rst
User can control skip_if_unavailable via ks_meta.
Fixes: #58
> Add ability to control skip_if_unavailable for task repo

- .packit.yaml
> Enable Fedora 33 chroot in Packit as a Service 

- IntegrationTests/src/bkr/inttest/server/test_kickstart.py
- Server/bkr/server/kickstart.py
- Server/bkr/server/model/scheduler.py
- documentation/user-guide/customizing-installation.rst
Some teams would like to have more flexibility about `<kickstart />`.
The problem is that we still defining minimum content for them.
With this patch, it is completely up to the user how kickstart will look like even within `job` and it is their responsibility to make sure that they will be operational.
Bug: [1831885](https://bugzilla.redhat.com/show_bug.cgi?id=1831885)
> Allow user to define whole kickstart for jobs

- Server/bkr/server/CSV_import_export.py
The following patch is making sure that we are not loading all `1:N` to memory all the time.
This may result in OOM if we are not careful enough because all items will be stored as `dict` in interpret before we start using it.
Resolves: #65 
> Store reasonable number of items into RAM during export

- Common/bkr/common/hub.py
Python 3.9 has removed the deprecated method 'encodestring' from base64 module.
It needs to be replaced by ' encodebytes'.
Signed-off-by: Xavi Hernandez <xhernandez@redhat.com>
> fix: base64.encodestring() doesn't exist in Python 3.9

- IntegrationTests/src/bkr/inttest/server/kickstarts/AtomicHost-defaults.expected
- IntegrationTests/src/bkr/inttest/server/kickstarts/Fedora18-harness-contained-custom.expected
- IntegrationTests/src/bkr/inttest/server/kickstarts/Fedora18-harness-contained.expected
- IntegrationTests/src/bkr/inttest/server/kickstarts/Fedora18-scheduler-defaults.expected
- IntegrationTests/src/bkr/inttest/server/kickstarts/Fedorarawhide-scheduler-defaults.expected
- IntegrationTests/src/bkr/inttest/server/kickstarts/RHVH-defaults.expected
- IntegrationTests/src/bkr/inttest/server/kickstarts/RedHatEnterpriseLinux6-manual-defaults-beaker-create-kickstart.expected
- IntegrationTests/src/bkr/inttest/server/kickstarts/RedHatEnterpriseLinux6-manual-defaults.expected
- IntegrationTests/src/bkr/inttest/server/kickstarts/RedHatEnterpriseLinux6-scheduler-defaults-beaker-create-kickstart.expected
- IntegrationTests/src/bkr/inttest/server/kickstarts/RedHatEnterpriseLinux6-scheduler-defaults.expected
- IntegrationTests/src/bkr/inttest/server/kickstarts/RedHatEnterpriseLinux6-scheduler-guest.expected
- IntegrationTests/src/bkr/inttest/server/kickstarts/RedHatEnterpriseLinux7-scheduler-defaults.expected
- IntegrationTests/src/bkr/inttest/server/kickstarts/RedHatEnterpriseLinuxAlternateArchitectures7-scheduler-defaults.expected
- Server/bkr/server/kickstarts/default
The kickstart 'install' command has been deprecated since Fedora 29 and
is being removed in Fedora 34.
ref: pykickstart/pykickstart#347.
Instead of removing it only for Fedora, we will drop it for RHEL as well as this is completely fine.
> Remove install kickstart command 

- Common/bkr/common/hub.py
We introduced an error in #75 
We need to silence it otherwise it will bother us in all reviews.
> Silence no-member pylint error for Python 3 encodebytes

- IntegrationTests/src/bkr/inttest/server/test_kickstart.py
- Server/bkr/server/model/distrolibrary.py
Disable security because we living on the edge.
> Disable SSH security for RHEL9

- documentation/whats-new/release-28.rst
New maintenance release to keep Beaker alive.
Fixes:
- Client works with 🐍 3.9
- Removed `install` from kickstart. This will enable F34 and EL9
- Make RHEL 9 ssh great again
> Release 28.1

- IntegrationTests/src/bkr/inttest/labcontroller/test_watchdog.py
- LabController/src/bkr/labcontroller/utils.py
When a guest recipe console log was being processed during beaker
upgrade, an exception was raised with call to startswith in
labcontroller.utils.get_console_files.  In the case of guest recipes,
it is possible for the system name to be None. This change recognizes
this case, reports this occurred, and discontinues getting console
files for this guest recipes.  Since exception is not raised, other recipes
will continue to get their console files.
Closes: BKR-5038
> Fix: Get console logs raises Exception

- IntegrationTests/src/bkr/inttest/labcontroller/test_proxy.py
- IntegrationTests/src/bkr/inttest/server/selenium/test_systems.py
- IntegrationTests/src/bkr/inttest/server/test_model.py
- Server/bkr/server/installopts.py
- Server/bkr/server/model/distrolibrary.py
- Server/bkr/server/model/inventory.py
- Server/bkr/server/model/scheduler.py
- Server/bkr/server/systems.py
- Server/server.cfg
This fixes #83.
Changed it for RHEL9+ and Fedora34+
> Fix deprecated kernel options for newer distros

- documentation/whats-new/release-28.rst
Maintenance release 28.2 Fixes:
* Replace deprecated kernel options for newer distros.
* No longer raise exception when getting console logs
for guest recipes.
> Docs: Maintenance release doc for 28.2

- .packit.yaml
Fedora 34 branched out, therefore we need to add new target.
Rawhide is baseline for Fedora 35 now.
> Add support for Fedora 34

- beaker.spec
As we are moving to CentOS Stream or RHEL 8 / Oracle Linux 8 / Whatever Linux 8 we can drop a bunch of things already.
I'm keeping python3 macro due to server, lc, etc.. because we didn't port this to Python 3 code base.
We will remove it later on.
> Remove obsolete macros and packages from specfile

- .stickler.yml
- Server/bkr/server/activity.py
Following things have changed:
- No more HTML render by default
- Dictionaries are merged w/o __add__, this is not supported in Python 3
- Sorted imports
> Make Activity endpoints JSON only

- Server/bkr/server/activity.py
- Server/bkr/server/authentication.py
- Server/bkr/server/controllers.py
Few minor things that blocked me to use Beaker from develop properly.
- BasicAuth doesn't require proxy users anymore to work as intended
- Auth removed from root controller as we don't have XMLRPC there anymore
- Python 6 implementation for Activities
> Make Beaker operational again

- Server/bkr/server/controllers.py
- Server/bkr/server/user.py
Users XMLRPC is not needed anymore.
Everything is exposed via HTTP API.
There was only one function for removing users.
This is covered by PATCH-ing the user.
endpoint
```
@app.route('/users/<path:username>', methods=['PATCH'])
```
> Remove obsolete Users XMLRPC

- .packit.yaml
- Fedora 32 is dead
- Fedora 35 is branched and can be used
- CentOS Stream 8 got renamed to avoid confusion from CentOS Stream 9
- CentOS Stream 9 added. This is completely new pre-release target
> Extend CI targets

- Server/bkr/server/model/distrolibrary.py
Installs of RHEL 7 up to 7.3 (including) are failing when anaconda could not recognize `%onerror` section. We should not mark those builds with `has_onerror`.
Feature was introduced here: [RHEL 7.4 release notes](https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/7/html/7.4_release_notes/new_features_installation_and_booting#BZ1412538)
> Fix: onerror is not supported on <=rhel7.3

- Server/bkr/server/snippets/grubport
This resolves the issue https://github.com/beaker-project/beaker/issues/147
The method to check if the system is unified grub.cfg setup follows scriptlet from grub2-common package.
Signed-off-by: Jun'ichi Nomura <junichi.nomura@nec.com>
> Do not modify /boot/efi/EFI/redhat/grub.cfg on unified grub.cfg setup

- .gitmodules
Unencrypted git protocol become obsolete and prohibited by some systems [0]. Some of our projects are dependent on `beaker-client` and `beaker-common`. However, pipenv locking fails due to old git protocol. This pull request contains fixed protocol in submodules.
I am opening PR into master to include the fix ASAP. If you have a different development workflow and it violates your plans, feel free to move it into `develop` branch.
[0] https://github.blog/2021-09-01-improving-git-protocol-security-github/
> [git] modules: use https instead of git

- .packit.yaml
- Client/run-tests.sh
- Client/src/bkr/client/tests/test_wizard.py
- Common/run-tests.sh
- beaker.spec
I cherry-picked commits from `develop` to align packit behavior.
Then I enable C9 and removed all obstacles.
This will be released under 28.5
Fixes #141
> Enable build on CentOS Stream 9

- documentation/whats-new/release-28.rst
> Release 28.3

- Server/bkr/server/distrotrees.py
Using None as a default scheme is problematic with the newest python.
It will produce the following error:
>>> url = 'http://foo.example.com/RHEL-8.7/compose/BaseOS/x86_64/os/'
>>> urlparse.urlparse(url, scheme=None).scheme
Traceback (most recent call last):
File "<stdin>", line 1, in <module>
File "/usr/lib64/python2.7/urlparse.py", line 145, in urlparse
tuple = urlsplit(url, scheme, allow_fragments)
File "/usr/lib64/python2.7/urlparse.py", line 201, in urlsplit
scheme = _remove_unsafe_bytes_from_url(scheme)
File "/usr/lib64/python2.7/urlparse.py", line 191, in _remove_unsafe_bytes_from_url
url = url.replace(b, "")
AttributeError: 'NoneType' object has no attribute 'replace'
> Don't use None as a key

- Makefile
Fixes: #172
Fixes: acfabb4bf441 ("Devel patch to activate beaker from local git tree")
> Fix submods target in Makefile

- Client/src/bkr/client/commands/cmd_job_results.py
The same result that was put in place for regular xml results is also needed for the junit results when running with python3.
> Update to fix junit results on python3

- Common/bkr/common/schema/beaker-job.rng
- IntegrationTests/src/bkr/inttest/server/test_jobs.py
- LabController/src/bkr/labcontroller/netboot.py
- LabController/src/bkr/labcontroller/provision.py
- LabController/src/bkr/labcontroller/test_netboot.py
- Server/bkr/server/alembic/versions/140c5eea2836_add_image_path_to_installation_table.py
- Server/bkr/server/jobs.py
- Server/bkr/server/labcontroller.py
- Server/bkr/server/model/installation.py
This allows for custom boot loaders to be used per installation.  Newer versions of RHEL may require newer versions of grub or the ppc64le boot loader to function properly.
> Add support for custom boot loaders

- .packit.yaml
- Common/bkr/common/xmlrpc2.py
- Common/bkr/common/xmlrpc3.py
Fixes https://github.com/beaker-project/beaker/issues/188
> Do not use ssl.wrap_socket removed in Python 3.12

- beaker.spec
Using GitHub Archive as a source allows us to create RPMs as soon as a new tag is present in the repository, instead of waiting until we have a mirror stored on Beaker-Project.org. Ideally, we would like to reverse this workflow: we publish the tag and then use automation to mirror it to Beaker-Project.org (with rest of the artifacts - e.g. RPMs )
We do the same thing for Restraint at this moment.
> Use GitHub Archive as source for tarball

- beaker.spec
GitHub archives are created with the repository name as a prefix.
For instance, requesting an archive from:
```
https://github.com/beaker-project/beaker/archive/beaker-28.3.tar.gz
``` 
results in a file named beaker-beaker-28.3.tar.gz, as indicated by the content-disposition header:
```
</snip>
< content-disposition: attachment; filename=beaker-beaker-28.3.tar.gz
</snip>
```
Although the Spectool and RPM toolchain store the file based on the requested path, resulting in beaker-28.3.tar.gz, the internal structure of the tarball reflects the original GitHub archive naming. This discrepancy can cause issues during the RPM build process.
This commit adjusts the %setup -n parameter in the spec file to align with the GitHub archive's internal structure, ensuring correct extraction and building. …
> Update -n parameter in %setup macro

- documentation/whats-new/index.rst
- documentation/whats-new/release-29.rst
> Release Notes 29

- .github/workflows/publish.yml
The last missing piece to ship Beaker, Release 29.
More work has been done on the bp.org repository, which will give us all the necessary artifacts.
Resolves: #186
> Build production RPMs as part of release pipeline

- Client/src/bkr/client/__init__.py
- Client/src/bkr/client/commands/cmd_workflow_xslt.py
- Client/src/bkr/client/tests/test_wizard.py
- Client/src/bkr/client/wizard.py
- IntegrationTests/src/bkr/inttest/client/test_update_inventory.py
- IntegrationTests/src/bkr/inttest/client/test_watchdogs_show.py
- IntegrationTests/src/bkr/inttest/client/test_workflow_simple.py
Candidate sites were found via
find . -iname '*.py' -exec pylint --disable all --enable W1401 {} +
and
git grep  '\<re\..*(["'"'].*\\\\"  | grep '\.py:'
Fixes https://github.com/beaker-project/beaker/issues/211
> Fix invalid escape sequences on Python 3.12 in client code

- Common/bkr/common/hub.py
The message attribute no longer exists in Python 3.  
Instead, we convert the message to string, append to it, and expose it via args. This approach works both on Python 2 and Python 3
Resolves: #210
> Refactor error message handling

- documentation/whats-new/release-29.rst
Create a new release 29.1.
This release features only small changes (as expected from Y releases). 
We incorporate only 2 fixes.
- Refactored error message handling when dealing with Kerberos realm settings. (#210)
- Fixed invalid escape sequences in Python 3.12 across various client code. (#211)
> Changelog for Release 29.1

- documentation/user-guide/job-xml.rst
The custom distro feature was added to beaker,
https://github.com/beaker-project/beaker-dev-docs/blob/master/proposals/allow-installation-user-defined-distro.rst But it was never documented.  This PR documents that and adds documentation for the image node which allows further customization by allowing you to specify the boot loader used for network installs.
> Update user docs to cover custom distro

- .github/workflows/review-checks.yml
This implementation was done for the Python 2 codebase and doesn't serve the purpose anymore. Linter will be added again once we are done with the Python 3 baseline.
> CI: Remove obsolete pylint implementation

- .github/workflows/review-checks.yml
This pull request locks the DB to MariaDB 10 to avoid random failures in test cases. We can extend the matrix if we want to support additional databases or versions, but we need to make sure we can configure them properly for production.
> CI: Use MariaDB 10-ubi as DB for tests

- .github/workflows/publish.yml
- .github/workflows/review-checks.yml
Get the GitHub CI working.
* Use `vault.centos.org` for CentOS 7 and CentOS 8
* Force use of node 16
* Use `artifact@v3` [1]
1. https://github.blog/changelog/2024-02-13-deprecation-notice-v1-and-v2-of-the-artifact-actions/
> chore(ci): make the CI work on GitHub

- IntegrationTests/src/bkr/inttest/labcontroller/__init__.py
- IntegrationTests/src/bkr/inttest/labcontroller/test_distro_import.py
- IntegrationTests/src/bkr/inttest/labcontroller/test_provision.py
- IntegrationTests/src/bkr/inttest/labcontroller/test_proxy.py
This is just a first draft of an onboard integration test package using Python 3. 
I do not expect the code to work at runtime, but the goal is to be able to run the code without syntax or import errors.
> Make integration tests for LC Python 2 and 3 syntax compatible

- Common/bkr/common/xmlrpc3.py
ex is not defined in this context, remove it and just log an error that the cleanup failed.
> xmlrpc3: remove missing arguments

- LabController/cron.hourly/beaker_expire_distros
- LabController/src/bkr/labcontroller/expire_distros.py
When the beaker_expire_distros hourly cron job ran, the MemoryError is seen on the lab controller as well as Server. This same error is seen when executing the bkr CLI 'bkr distro-trees-list --limit=8000 --labcontroller=hostname | grep "ID:" | wc -l'
As it turns out, expire_distros is calling the same underlying get method.  The error is sporadic.  It is likely due to difficulty attaining a contiguous memory chunk for a lot of data.  The solution is to get smaller chunks.  Similar filters as the cli distro-trees-list are now allow thru expired_distros.py which passes them to the same get operation. These filters also allows for more variation for beaker_expire_distros. Stepping thru architectures seemed to be the best choice of filters for the chunks.  When --arch=all, the …
> MemoryError seen on expire_distros execution

- IntegrationTests/src/bkr/inttest/labcontroller/test_pxemenu.py
- LabController/src/bkr/labcontroller/pxemenu-templates/efi-grub-menu
- LabController/src/bkr/labcontroller/pxemenu-templates/grub2-menu
- LabController/src/bkr/labcontroller/pxemenu-templates/ipxe-menu
- LabController/src/bkr/labcontroller/pxemenu-templates/pxelinux-menu
- LabController/src/bkr/labcontroller/pxemenu.py
For latest distros, the variables 'method' and 'repos' are not supported in beaker pxemenu.  Replace with 'inst.repos' instead.  The latest distros are
RHEL9, CentOSStream9, FedoraRawhide, FedoraELN, and Fedora34 and up.
> Support latest distro args in pxemenu

- IntegrationTests/src/bkr/inttest/server/test_kickstart.py
- Server/bkr/server/snippets/grubport
Beaker users reported grub.cfg files being overwritten by Beaker causing job failures.  I determined that this occurs only when the system is configured with
Install Options --> Kickstart Metadata --> grubport=0x03f8
This grubport config causes the grubport snippet to expand in the kickstart file.  When looking at the two possible grub.cfg files, it looks like RHEL team now using /boot/efi/EFI/redhat/grub.cfg as a programmable link to /boot/grub2/grub.cfg file. To continue to support configuration of serial port, this changeset will only try to configure /boot/grub2/grub.cfg for RHEL9.  All other distros will remain the unchanged.
> grubport snippet fails for RHEL9

- IntegrationTests/src/bkr/inttest/assertions.py
- IntegrationTests/src/bkr/inttest/client/test_system_status.py
- IntegrationTests/src/bkr/inttest/client/test_task_add.py
- IntegrationTests/src/bkr/inttest/client/test_update_openstack_trust.py
- IntegrationTests/src/bkr/inttest/http_server.py
- IntegrationTests/src/bkr/inttest/kickstart_helpers.py
- IntegrationTests/src/bkr/inttest/labcontroller/test_distro_import.py
- IntegrationTests/src/bkr/inttest/labcontroller/test_watchdog.py
- IntegrationTests/src/bkr/inttest/mail_capture.py
- IntegrationTests/src/bkr/inttest/server/requests_utils.py
- IntegrationTests/src/bkr/inttest/server/test_beakerd.py
- IntegrationTests/src/bkr/inttest/server/test_database_migration.py
- IntegrationTests/src/bkr/inttest/server/test_jobs.py
- IntegrationTests/src/bkr/inttest/server/test_kickstart.py
- IntegrationTests/src/bkr/inttest/server/test_lab_controller.py
- IntegrationTests/src/bkr/inttest/server/test_mail.py
- IntegrationTests/src/bkr/inttest/server/test_model.py
- IntegrationTests/src/bkr/inttest/server/test_rdf.py
- IntegrationTests/src/bkr/inttest/server/test_reporting_queries.py
- IntegrationTests/src/bkr/inttest/server/test_utilisation.py
- IntegrationTests/src/bkr/inttest/server/tools/test_create_kickstart.py
- IntegrationTests/src/bkr/inttest/server/tools/test_init.py
- IntegrationTests/src/bkr/inttest/server/tools/test_log_delete.py
- IntegrationTests/src/bkr/inttest/server/webdriver_utils.py
This pull request only contains changes to make it compatible with Python 3 in terms of syntax and imports. 
We still need to convert part of the integration suite to make it work. There are a bunch of dependencies on the server part.
Unused imports are removed to reduce the issues with transition
> Make tests compatible with Python 3
